services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: true  # Automatically registers your services as commands, event subscribers, etc.

    Xact\TypeHintHydrator\TypeHintHydrator:
        public: true
        autowire: true
